### ISSUE TITLE
Geofencing iOS SDK - Define tracking parameters from a Json or an URL

### ISSUE THREAD

**Issue by lpernelle-wgs** [Woosmap/woosmap-geofencing-ios-sdk#56]
# Problem
## What

Simplify Woosmap Geofencing SDK tracking configuration.
Externalize WoosmapGeofencing SDK tracking configuration, upload Json data in the SDK ~~and refresh these data periodically~~.
## Why

In the current version, to initialize and start location collection, client app has to use a standard tracking profile (liveTracking, passiveTracking or visitTracking) or manually set each parameter in the SDK. The first method is too restrictive and the second one is too complexe. 

## Who

Clients | Customer Care | Sales | Marketing

# Solution
## How

- [x] Edit the startTracking method to allow client app to provide URL linked to a Json file
- [x] If the custom Json file doesn't respect the Json schema, an error message is logged in the client app and SDK continues with current setting values
- [x] ~~Add an automatic process to refresh the Json file upload periodically (more details in the Supporting Information section)~~
- [x] ~~Add a SDK setting parameter to define the gap between two Json file refresh~~

### Supporting Information

**State diagram**
![TrackingProfile](https://user-images.githubusercontent.com/79836861/147668246-ee4082a5-ff88-4cc6-aa53-19371c659f6d.jpg)

<details><summary>JSON Schema</summary>

```JSON
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Woosmap Geofencing SDK - Tracking profile Json schema",
    "description": "Configuration file ",
    "properties": {
        "trackingProfileRefreshDelay": {
            "description": "Minimum number of day to wait before refresh the custom profile. A value of 0 indicates that no refresh is performed by the SDK.",
            "type": "integer",
            "minimum": 0
        },
        "trackingEnable": {
            "description": "Enable this parameter to start collecting location",
            "type": "boolean"
        },
        "foregroundLocationServiceEnable": {
            "description": "ANDROID ONLY - Enable this parameter to use the foreground service to collect location when the app is in background.",
            "type": "boolean"
        },
        "modeHighFrequencyLocation": {
            "description": "Enable this parameter to have a higher frequency of location updates.",
            "type": "boolean"
        },
        "visitEnable": {
            "description": "Enable this parameter to detect user's stops",
            "type": "boolean"
        },
        "classificationEnable": {
            "description": "Enable this parameter to classify the all zone of interest",
            "type": "boolean"
        },
        "minDurationVisitDisplay": {
            "description": "",
            "type": "integer",
            "minimum": 0
        },
        "radiusDetectionClassifiedZOI": {
            "description": "",
            "type": "integer",
            "minimum": 0
        },
        "distanceDetectionThresholdVisits": {
            "description": "",
            "type": "integer",
            "minimum": 0
        },
        "creationOfZOIEnable": {
            "description": "Enable this parameter to automically create zone of interest from collected visits",
            "type": "boolean"
        },
        "accuracyVisitFilter": {
            "description": "",
            "type": "integer",
            "minimum": 0
        },
        "currentLocationTimeFilter": {
            "description": "",
            "type": "integer",
            "minimum": 0
        },
        "currentLocationDistanceFilter": {
            "description": "",
            "type": "integer",
            "minimum": 0
        },
        "accuracyFilter": {
            "description": "",
            "type": "integer",
            "minimum": 0
        },
        "searchAPI": {
            "description": "In this object, find all parameters related to the Woosmap Search API.",
            "type": "object",
            "properties": {
                "searchAPIEnable": {
                    "description": "Enable this parameters to request the Woosmap Search API regularly to retrieve nearest POIs",
                    "type": "boolean"
                },
                "searchAPICreationRegionEnable": {
                    "description": "Enable this parameters to automatically create a circle geofence around each POIs retrieved from the request to the Woosmap Search API",
                    "type": "boolean"
                },
                "searchAPITimeFilter": {
                    "description": "Minimum number of seconds to wait before send a new request to the Woosmap Search API.",
                    "type": "integer",
                    "minimum": 0
                },
                "searchAPIDistanceFilter": {
                    "description": "Minimum number of meters to wait before send a new request to the Woosmap Search API.",
                    "type": "integer",
                    "minimum": 0
                },
                "searchAPIRefreshDelayDay": {
                    "description": "Number of day to wait before force to send a new request to the Woosmap Search API.",
                    "type": "integer",
                    "minimum": 1
                }
            },
            "required": [
                "searchAPIEnable",
                "searchAPICreationRegionEnable",
                "searchAPITimeFilter",
                "searchAPIDistanceFilter",
                "searchAPIRefreshDelayDay"
            ]
        },
        "distanceAPIEnable": {
            "description": "DEPRECATED - Enable this parameter to automatically send a request to Woosmap Distance API after a request to the Search API.",
            "type": "boolean"
        },
        "outOfTimeDelay": {
            "description": "",
            "type": "integer",
            "minimum": 0
        },
        "dataDurationDelay": {
            "description": "",
            "type": "integer",
            "minimum": 0
        },
        "distance": {
            "description": "In this object, find all parameters related to the Distance provider.",
            "type": "object",
            "properties": {
                "distanceProvider": {
                    "description": "Use this parameter to define which Distance provider will be used to retrieve distance and duration data.",
                    "type": "string",
                    "enum": ["WoosmapDistance", "WoosmapTraffic"]
                },
                "distanceMode": {
                    "description": "Use this parameter to define the travel mode related to the request to the Distance provider.",
                    "type": "string",
                    "enum": ["driving", "walking", "cycling"]
                },
                "distanceRouting": {
                    "description": "Use this parameter to define the Woosmap Traffic API routing parameter",
                    "type": "string"
                },
                "distanceUnits": {
                    "description": "Use this parameter to define the distance unit related to the request to the Distance provider.",
                    "type": "string",
                    "enum": ["metric", "imperial"]
                },
                "distanceLanguage": {
                    "description": "Use this parameter to define the language related to the request to the Distance provider.",
                    "type": "string"
                },
                "distanceMaxAirDistanceFilter": {
                    "description": "Maximum air distance between the user location and the isochrone geofence center to justify the ETA has to be calculated.",
                    "type": "integer",
                    "maximum": 1000000,
                    "minimum": 0
                },
                "distanceTimeFilter": {
                    "description": "Minimum number of seconds to wait before send a new request to the Distance provider.",
                    "type": "integer"
                }
            },
            "required": [
                "distanceProvider",
                "distanceMode",
                "distanceUnits",
                "distanceMaxAirDistanceFilter",
                "distanceTimeFilter"
            ]
        }
    },
    "required": [
        "trackingEnable",
        "foregroundLocationServiceEnable",
        "modeHighFrequencyLocation",
        "visitEnable",
        "currentLocationTimeFilter",
        "currentLocationDistanceFilter",
        "accuracyFilter",
        "searchAPI",
        "distanceAPIEnable",
        "outOfTimeDelay",
        "dataDurationDelay",
        "distance",
        "FCMEnable"
    ]
}
```

</details>

### Expected Change Level

Major

# Acceptance Criteria (AC)

# Documentation

Internal: SwiftDoc Reference
External: developers.woosmap.com
